# Site
repository: gyogeshchandra/gyogeshchandra.github.io
# favicon: images/favicon.ico

# Personal info
name: G Yogesh Chandra
title: Senior Software Engineer - Lead
email: er.yogeshchandra@gmail.com
website: https://gyogeshchandra.github.io

# Social demo in git
#twitter_username: yogesh
github_username:  gyogeshchandra
# facebook_username: gyogeshchandra
# flickr_username: yogesh
linkedin_username: gyogeshchandra
instagram_username: yogesh.live_life
# pinterest_username: yogesh
# googleplus_username: +yogesh

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Yogesh Chandra and I work as senior software engineer Lead with Walmart Global Tech. I have a great experience in making software and web apps.

  <mark>SKILLS : </mark><br/>
      • Expertise in Python, Perl and GoLang <br>
      • Database knowledge in Mysql, Oracle, PostgreSQL and Cassandra <br>
      • Good Understanding of Flask, Django and FastAPI <br>
      • Good Understanding of Javascript, ReactJS, HTML and CSS <br>
      • Able to work with Docker, Ansible, Ansible Tower and Jenkins<br>
      • Good understanding of tools like Git, Jira, Jenkins, Apache server, UWSGI <br>
      • Operating systems - Linux, Unix, Macos and Windows <br>

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Playing Table Tennis
   - Playing Piano
   - Trekking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
