# Site
repository: gyogeshchandra/gyogeshchandra.github.io
# favicon: images/favicon.ico

# Personal info
name: G Yogesh Chandra
title: Software Engineer II
email: er.yogeshchandra@gmail.com
website: https://gyogeshchandra.github.io

# Social links
twitter_username: facespics
github_username:  gyogeshchandra
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: yogesh.live_life
linkedin_username: gyogeshchandra
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Yogesh Chandra and I work as software engineer II in Akamai Technologies. I have a great experience in making software and web apps.
  I am most skilled in: <mark>Python</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
